services:
    sikribo_app:
        build:
            context: . # Context adalah direktori saat ini
            dockerfile: Dockerfile # Gunakan Dockerfile di direktori saat ini
        container_name: sikribo_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage:/var/www/storage
        ports:
            - ":9000"
        env_file:
            - .env-stages
        networks:
            - sikribo

    webserver_sikribodo:
        image: nginx:stable
        container_name: webserver_sikribodo
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
        networks:
            - sikribo
        depends_on:
            - sikribo_app

    db_sikribo:
        image: mysql:8.0
        container_name: db_sikribo
        restart: unless-stopped
        ports:
            - ":3306"
        environment:
            MYSQL_DATABASE: sikribo
            MYSQL_USER: sikribo
            MYSQL_ROOT_PASSWORD: rahasia
        volumes:
            - sikribodbdata:/var/lib/mysql
        networks:
            - sikribo

volumes:
    sikribodbdata:

networks:
    sikribo:
