services:
    sikribo_app:
        image: bankwonosobo/laravel-sikribo:latest
        container_name: sikribo_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage:/var/www/storage
        environment:
            APP_NAME: "Sikribo Laravel"
            APP_ENV: production
            APP_DEBUG: "true"
            APP_KEY: base64:Ke2Tt9EwNksfv/Ov54dLHwN0ZPicYIc8e/s+7bwvw3s=
            DB_CONNECTION: mysql
            DB_HOST: db_sikribo
            DB_PORT: 3306
            DB_DATABASE: sikribodb
            DB_USERNAME: sikribodb
            DB_PASSWORD: sikribodb
        networks:
            - sikribo-network
        depends_on:
            - db_sikribo

    webserver_sikribodo:
        image: nginx:stable
        container_name: webserver_sikribodo
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8081:80"
        networks:
            - sikribo-network
        depends_on:
            - sikribo_app

    db_sikribo:
        image: mysql:8.0
        container_name: db_sikribo
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sikribodb
            MYSQL_USER: sikribodb
            MYSQL_PASSWORD: sikribodb
        volumes:
            - sikribodbdata:/var/lib/mysql
        networks:
            - sikribo-network

volumes:
    sikribodbdata:

networks:
    sikribo-network:
        driver: bridge
