name: Sikribo Laravel Docker CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP 7.4
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, zip, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # # Step 2: Cache Composer dependencies (opsional)
      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Step 3: Install dependencies Laravel
      - name: Install Composer Dependencies
        run: |
          composer install

      # Step 4: Set Application Key
      - name: Set Application Key
        run: php artisan key:generate

      # Step 5: Wait for MySQL to Be Ready
      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h 127.0.0.1 -u root -proot --silent; then
              echo "MySQL is ready";
              exit 0;
            fi
            echo "Waiting for MySQL...";
            sleep 5;
          done
          exit 1

      # Step 6: Run Database Migrations
      - name: Run Database Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: testuser
          DB_PASSWORD: testpass
        run: php artisan migrate --force

      # Step 4: Login ke Docker Hub atau GHCR
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Step 5: Build image Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel-sikribo:latest .

      # Step 6: Push image ke Docker Hub atau GHCR
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/laravel-sikribo:latest

      # Step 7: Run Tests
      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: testuser
          DB_PASSWORD: testpass
        run: php artisan test
